export const CATEGORY_MOCK = [
  { header: 'Revenue' },
  { name: 'SaaS Revenue', group: 'Revenue' },
  { name: 'Services Revenue', group: 'Revenue' },
  { divider: true },
  { header: 'Less Cost of Sales' },
  { name: 'COGS Item 1 (SaaS)', group: 'Less Cost of Sales' },
  { name: 'Jane Smith ', group: 'Less Cost of Sales' },
  { name: 'John Smith', group: 'Less Cost of Sales' },
  { name: 'Sandra Williams', group: 'Less Cost of Sales' },
  { divider: true },
  { header: 'Operations' },
  { name: 'Ops Compensation', group: 'Operations' },
  { name: 'Ops Payroll Taxes', group: 'Operations' },
  { name: 'Ops Benefits', group: 'Operations' },
  { name: 'Ops Contractors', group: 'Operations' },
  { name: 'Ops1', group: 'Operations' },
  { name: 'Ops2', group: 'Operations' },
  { name: 'Ops3', group: 'Operations' },
  { divider: true },
  { header: 'Sales' },
  { name: 'Sales Compensation', group: 'Sales' },
  { name: 'Sales Commissions', group: 'Sales' },
  { name: 'Sales Payroll Taxes', group: 'Sales' },
  { name: 'Sales Benefits', group: 'Sales' },
  { name: 'Sales Contractors', group: 'Sales' },
  { name: 'Sales - Meals, Ent & Travel', group: 'Sales' },
  { name: 'Sales Consulting - Subcontracting - Business Development', group: 'Sales' },
]
